// frontend/angular-app/src/app/components/students/students.component.ts
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { ApiService } from "../../services/api.service";
import { Student } from "../../models/types";

@Component({
  selector: "app-students",
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="card shadow border-0">
      <div
        class="card-header bg-white d-flex justify-content-between align-items-center"
      >
        <h4 class="mb-0 text-primary">Student Management</h4>
        <input
          type="text"
          class="form-control w-25"
          placeholder="Search by name..."
          [(ngModel)]="searchTerm"
        />
      </div>
      <div class="card-body">
        <div class="row mb-4 bg-light p-3 rounded">
          <h5>{{ selectedStudent.studentId ? "Edit" : "Add" }} Student</h5>
          <div class="col-md-3">
            <input
              [(ngModel)]="selectedStudent.fullName"
              class="form-control"
              placeholder="Full Name"
            />
          </div>
          <div class="col-md-3">
            <input
              [(ngModel)]="selectedStudent.email"
              class="form-control"
              placeholder="Email"
            />
          </div>
          <div class="col-md-2">
            <input
              type="date"
              [(ngModel)]="selectedStudent.dateOfBirth"
              class="form-control"
            />
          </div>
          <div class="col-md-2">
            <input
              [(ngModel)]="selectedStudent.contactNumber"
              class="form-control"
              placeholder="Phone"
            />
          </div>
          <div class="col-md-2">
            <button (click)="save()" class="btn btn-success w-100">Save</button>
          </div>
        </div>

        <table class="table table-hover">
          <thead class="table-light">
            <tr>
              <th>ID</th>
              <th>Full Name</th>
              <th>Email</th>
              <th>DOB</th>
              <th>Phone</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let s of filteredStudents()">
              <td>{{ s.studentId }}</td>
              <td>{{ s.fullName }}</td>
              <td>{{ s.email }}</td>
              <td>{{ s.dateOfBirth | date }}</td>
              <td>{{ s.contactNumber }}</td>
              <td>
                <button
                  (click)="edit(s)"
                  class="btn btn-sm btn-info me-2 text-white"
                >
                  <i class="bi bi-pencil"></i>
                </button>
                <button
                  (click)="delete(s.studentId!)"
                  class="btn btn-sm btn-danger"
                >
                  <i class="bi bi-trash"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `,
})
export class StudentsComponent implements OnInit {
  students: Student[] = [];
  searchTerm: string = "";
  selectedStudent: Student = this.reset();

  constructor(private api: ApiService) {}

  ngOnInit() {
    this.load();
  }

  load() {
    this.api.getStudents().subscribe((res) => (this.students = res));
  }

  reset() {
    return { fullName: "", email: "", dateOfBirth: "", contactNumber: "" };
  }

  filteredStudents() {
    return this.students.filter((s) =>
      s.fullName.toLowerCase().includes(this.searchTerm.toLowerCase()),
    );
  }

  save() {
    this.api.saveStudent(this.selectedStudent).subscribe(() => {
      this.load();
      this.selectedStudent = this.reset();
    });
  }

  edit(s: Student) {
    this.selectedStudent = { ...s, dateOfBirth: s.dateOfBirth.split("T")[0] };
  }

  delete(id: number) {
    if (confirm("Delete student?"))
      this.api.deleteStudent(id).subscribe(() => this.load());
  }
}

// frontend/react-app/src/components/Students.js
import React, { useState, useEffect } from 'react';
import { getStudents, addStudent, deleteStudent } from '../services/api';

const Students = () => {
    const [students, setStudents] = useState([]);
    const [search, setSearch] = useState('');
    const [form, setForm] = useState({ fullName: '', email: '', dateOfBirth: '', contactNumber: '' });

    useEffect(() => { load(); }, []);

    const load = () => getStudents().then(res => setStudents(res.data)).catch(() => {});

    const handleSubmit = async (e) => {
        e.preventDefault();
        await addStudent(form);
        setForm({ fullName: '', email: '', dateOfBirth: '', contactNumber: '' });
        load();
    };

    const handleDelete = async (id) => {
        if (window.confirm('Delete student?')) {
            await deleteStudent(id);
            load();
        }
    };

    const filtered = students.filter(s => s.fullName.toLowerCase().includes(search.toLowerCase()));

    return (
        <div className="container">
            <div className="row">
                <div className="col-md-4">
                    <div className="card shadow-sm p-3 mb-4">
                        <h5>Add Student</h5>
                        <form onSubmit={handleSubmit}>
                            <input className="form-control mb-2" placeholder="Full Name" value={form.fullName} onChange={e => setForm({...form, fullName: e.target.value})} required />
                            <input className="form-control mb-2" placeholder="Email" type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})} required />
                            <input className="form-control mb-2" type="date" value={form.dateOfBirth} onChange={e => setForm({...form, dateOfBirth: e.target.value})} required />
                            <input className="form-control mb-3" placeholder="Phone" value={form.contactNumber} onChange={e => setForm({...form, contactNumber: e.target.value})} required />
                            <button className="btn btn-primary w-100">Add Student</button>
                        </form>
                    </div>
                </div>
                <div className="col-md-8">
                    <div className="d-flex justify-content-between mb-3">
                        <h3>Student List</h3>
                        <input className="form-control w-50" placeholder="Filter by name..." onChange={e => setSearch(e.target.value)} />
                    </div>
                    <table className="table table-bordered bg-white shadow-sm">
                        <thead className="table-secondary">
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Contact</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {filtered.map(s => (
                                <tr key={s.studentId}>
                                    <td>{s.fullName}</td>
                                    <td>{s.email}</td>
                                    <td>{s.contactNumber}</td>
                                    <td>
                                        <button className="btn btn-danger btn-sm" onClick={() => handleDelete(s.studentId)}>
                                            <i className="bi bi-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default Students;
